# Generated by Django 3.2.6 on 2022-05-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('Roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Class', models.CharField(blank=True, max_length=4, null=True)),
                ('School', models.CharField(blank=True, max_length=40, null=True)),
                ('Mobile', models.BigIntegerField()),
                ('Address', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcadamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maths', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDetails.studentinfo')),
            ],
        ),
    ]
